/**
 * Centralized registry for all backend API endpoints.
 * Use these constants instead of hardcoded strings in services.
 */
export const AppEndpoints = {
  AUTH: {
    LOGIN: "/auth/login",
  },
  FAIRS: {
    BASE: "/fairs",
    BY_ID: (id: string) => `/fairs/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/fairs/${id}/toggle-active`,
  },
  VISITORS: {
    BASE: "/visitors",
    BY_ID: (id: string) => `/visitors/${id}`,
  },
  CHECKINS: {
    BASE: "/checkins",
    TODAY: "/checkins/today",
  },
  USERS: {
    BASE: "/users",
    BY_ID: (id: string) => `/users/${id}`,
  },
  STANDS: {
    BASE: "/finance/stands",
    CONFIGURE: "/finance/stands/configure",
    AVAILABLE: "/finance/stands/available",
    OCCUPIED: "/finance/stands/occupied",
    STATS: "/finance/stands/stats",
    BY_ID: (id: string) => `/finance/stands/${id}`,
    LINK_REVENUE: (id: string) => `/finance/stands/${id}/link-revenue`,
    UNLINK_REVENUE: (id: string) => `/finance/stands/${id}/unlink-revenue`,
  },
  PARTNERS: {
    BASE: "/partners",
    ME: "/partners/me",
    BY_ID: (id: string) => `/partners/${id}`,
    FINANCIAL_SUMMARY: (partnerId: string) => `/partners/${partnerId}/financial-summary`,
    AVAILABLE_PERCENTAGE: "/partners/available-percentage",
    WITHDRAWALS: (partnerId: string) => `/partners/${partnerId}/withdrawals`,
    WITHDRAWALS_BY_FAIR: (partnerId: string, fairId: string) => `/partners/${partnerId}/withdrawals/fair/${fairId}`,
    APPROVE_WITHDRAWAL: (id: string) => `/partners/withdrawals/${id}/approve`,
    REJECT_WITHDRAWAL: (id: string) => `/partners/withdrawals/${id}/reject`,
    UPDATE_WITHDRAWAL: (id: string) => `/partners/withdrawals/${id}`,
    DELETE_WITHDRAWAL: (id: string) => `/partners/withdrawals/${id}`,
    BY_WITHDRAWAL_ID: (id: string) => `/partners/withdrawals/${id}`,
  },
  FINANCE: {
    ENTRY_MODELS: "/finance/entry-models",
    ENTRY_MODEL_BY_ID: (id: string) => `/finance/entry-models/${id}`,
    CLIENTS: "/finance/clients",
    CLIENT_BY_ID: (id: string) => `/finance/clients/${id}`,
    CLIENT_BY_EMAIL: (email: string) => `/finance/clients/email/${email}`,
    CLIENT_BY_CNPJ: (cnpj: string) => `/finance/clients/cnpj/${cnpj}`,
    CATEGORIES: "/finance/categories",
    CATEGORY_BY_ID: (id: string) => `/finance/categories/${id}`,
    CATEGORIES_BY_FAIR: (fairId: string) => `/categories/fair/${fairId}`,
    ACCOUNTS: "/accounts",
    ACCOUNT_BY_ID: (id: string) => `/accounts/${id}`,
    CASH_FLOW_DISTRIBUTE: (fairId: string) => `/cash-flow/distribute-profit/${fairId}`,
    CASH_FLOW_ANALYSIS: (fairId: string) => `/cash-flow/analysis/fair/${fairId}`,
    REVENUES: "/finance/revenues",
    REVENUE_BY_ID: (id: string) => `/finance/revenues/${id}`,
    REVENUE_BY_CLIENT: (clientId: string) => `/finance/revenues/client/${clientId}`,
    REVENUE_CANCEL: (id: string) => `/finance/revenues/${id}/cancel`,
    REVENUE_STATS: (fairId: string) => `/finance/revenues/stats/${fairId}`,
    REVENUE_KPIS: "/finance/kpis",
    REVENUE_TOP_COMPANIES: "/finance/top-empresas",
    REVENUE_BY_TYPE: "/finance/revenues/analytics/by-type",
    REVENUE_BY_MODEL: "/finance/revenues/analytics/by-model",
    REVENUE_INSTALLMENTS_GENERATE: (id: string) => `/finance/revenues/${id}/installments/generate`,
    REVENUE_INSTALLMENT_UPDATE: (id: string) => `/finance/revenues/installment/${id}`,
    REVENUE_INSTALLMENT_PAY: (id: string) => `/finance/revenues/installment/${id}/confirm-payment`,
    REVENUE_ATTACHMENTS: (id: string) => `/finance/revenues/${id}/attachments`,
    REVENUE_ATTACHMENT_BY_ID: (revenueId: string, attachmentId: string) => `/finance/revenues/${revenueId}/attachments/${attachmentId}`,
    EXPENSES: "/expenses",
    EXPENSE_BY_ID: (fairId: string, id: string) => `/fairs/${fairId}/expenses/${id}`,
    EXPENSES_BY_FAIR: (fairId: string) => `/fairs/${fairId}/expenses`,
    EXPENSES_TOTAL: (fairId: string) => `/fairs/${fairId}/expenses/total`,
    EXPENSES_BY_CATEGORY: (fairId: string) => `/fairs/${fairId}/expenses/total-by-category`,
    EXPENSES_BY_ACCOUNT: (fairId: string) => `/fairs/${fairId}/expenses/total-by-account`,
  },
  MARKETING: {
    EMAILS_ABSENT: "/emails/marketing/absent-visitors",
  },
  WITHDRAWALS: {
    BASE: "/partners/withdrawals",
    BY_ID: (id: string) => `/partners/withdrawals/${id}`,
    APPROVE: (id: string) => `/partners/withdrawals/${id}/approve`,
    REJECT: (id: string) => `/partners/withdrawals/${id}/reject`,
  },
  DASHBOARD: {
    OVERVIEW: "/dashboard/overview",
    VISITORS_CHECKED_IN: "/dashboard/visitors/checked-in",
    VISITORS_CATEGORY: "/dashboard/visitors/category",
    VISITORS_ORIGIN: "/dashboard/visitors/origin",
    VISITORS_SECTORS: "/dashboard/visitors/sectors",
    ABSENT_VISITORS: "/dashboard/absent-visitors",
    CONVERSIONS_HOW_DID_YOU_KNOW: "/dashboard/conversions/how-did-you-know",
  },
  FAIR_PARTNERS: {
    BASE: "/fair-partners",
    BY_FAIR: (fairId: string) => `/fair-partners/fair/${fairId}`,
    BY_PARTNER: (partnerId: string) => `/fair-partners/partner/${partnerId}`,
    ME_FAIRS: "/fair-partners/me/fairs",
    BY_ID: (id: string) => `/fair-partners/${id}`,
    SUMMARY: (fairId: string) => `/fair-partners/fair/${fairId}/summary`,
    FINANCIAL_SUMMARY: (fairId: string, partnerId: string) => `/fair-partners/fair/${fairId}/partner/${partnerId}/financial-summary`,
    AVAILABLE_PERCENTAGE: (fairId: string) => `/fair-partners/fair/${fairId}/available-percentage`,
  }
} as const;
